### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gvx111** [NonFactors/MVC6.Template#1]
Can not download automapper. 
How fix it?

**Comment by Muchiachio** [comment]
Hmm, seems to be working fine on two of my machines.
Make sure you are using:
- VS 2015 RTM with [beta6 tools](http://www.microsoft.com/en-us/download/details.aspx?id=48222) installed.
- 1.0.0-beta6 clr dnx runtime.
- Stable nuget.org feed.

**Comment by gvx111** [comment]
Severity	Code	Description	Project	File	Line	Source
Error	CS0246	The type or namespace name 'AutoMapper' could not be found (are you missing a using directive or an assembly reference?)	MvcTemplate.Data.DNX 4.5.1	MvcTemplate.Data\Core\Select.cs	1	IntelliSense

Severity	Code	Description	Project	File	Line	Source
Error		The dependency Microsoft.AspNet.Mvc.TagHelpers >= 6.0.0-beta6 could not be resolved.	MvcTemplate.Components	\MvcTemplate.Components\project.json	10	Build

Severity	Code	Description	Project	File	Line	Source
Error		The dependency BCrypt-Official >= 0.1.109 could not be resolved.	MvcTemplate.Components	MvcTemplate.Components\project.json	8	Build

Can not download dependencies what can ido?

**Comment by Muchiachio** [comment]
While searching for a solution for the problem with the dependency not being possible to resolve, I stumbled over this blog post: http://iamnotmyself.com/.... It also mentions the command `dnvm use 1.0.0-beta6` followed by the command `dnu restore` on the root of the project. And that seems to do the trick. The dnu restore command timed out a few times, but after 3 tries, it completed a successful restore for him.

**Comment by gvx111** [comment]
Its not fixed. can you give me your skype? i will add you.

**Comment by Muchiachio** [comment]
Sorry, I'm not using skype.
Did you try creating a new web project from VS and adding these references, to see if they can be restored from nuget?

**Comment by gvx111** [comment]
Yes Its downloaded in Empty Project

**Comment by Muchiachio** [comment]
Did you create the database with `dnx . ef migration apply`?
I will use dnx core then it will support most of the stuff dnx451 does.

**Comment by Muchiachio** [comment]
Closing as you seemed to fixed your issues.
