### ISSUE TITLE
Passhash

### ISSUE THREAD

**Issue by murat0058** [NonFactors/MVC6.Template#10]
what is the Password ?
$2b$13$ouxA6L7QZ/eSeVZD8lawSOEwtRn/hOoRY67Pwaj/WJaZe7S4.cHJC

My proje name :   MvcAdmin
Password:             Passw0rd

**Comment by Muchiachio** [comment]
As the comment next to it says, `// Will be generated on project rename`, you should first run project renaming tool which will ask for your password.

**Comment by murat0058** [comment]
I did what you said but it didnt work. How can I reset the password or How can I get a new password or How can I learn already exisiting pasword?

**Comment by Muchiachio** [comment]
Sorry, there was a bug in renaming code, you can re-download and try renaming again.

**Comment by murat0058** [comment]
ok
