### ISSUE TITLE
Scaffolding

### ISSUE THREAD

**Issue by FrancoRodrigues** [NonFactors/MVC6.Template#14]
I don't understand how scaffolding works on this new version... do you have a sample?

**Comment by Muchiachio** [comment]
It's not currently available. I had it working with my own tool on core 1, but after tooling update in asp net core 2 I could not get it working in any reasonable amount of hours I tried, so i just gave up for now.

I'm revisiting this problem from time to time but I only got it working on netcoreapp platform.

**Comment by FrancoRodrigues** [comment]
Ok them, i will study how can we make this works on aspnetcore2 and let you know if I find something
