### ISSUE TITLE
Could you create some minimum documentation for creating a simple new view/controller/model ? 

### ISSUE THREAD

**Issue by punkouter2018** [NonFactors/MVC6.Template#15]
I tried and I could not get the navigation item to show and also problems with authorization. I only have the Admin controllers to use as a reference. But want to create a general User page.

I can give you all the steps I have taken if that would help  ?

**Comment by Muchiachio** [comment]
You can find all the needed new file templates in this [folder](https://github.com/NonFactors/MVC6.Template/tree/94d7c9cc4168ed75301a0683d7773235f597d2cc/src/MvcTemplate.Web/Templates/Module).
After you created those there are few gluing steps to make.
- Add properties to model and view objects.
- Add EF migration to data project.
- Add needed permissions to `Configuration.cs` seed method.
- Add resources base on your (area, controller, action) naming in
    - `/Resources/Views/<Area>/<Controller>/<View>/<Titles|Validations>.resx`
    - `/Resources/Permissions/<Area|Controller|Action>/Titles.resx.`
    - `/Resources/<Headers|Pages>.resx.`
    - `/Resources/SiteMap/Titles.resx.`
- Add sitemap entries to `/Web/Mvc.sitemap`.

**Comment by Muchiachio** [comment]
It's my package. I can't get it working on core 2, so there is no automated way to use them for now.

**Comment by punkouter2018** [comment]
Ok. Could you create a sample 'TodoItem' generic object that shows the minimum pieces you need to introduce to perform CRUD on  ? I couldn't get my own object to work :( 


but it seems like a really interesting template Id like to use if I could understand better and get it working. 

Or a solution to the template generator for .net core 2.0 would be even better.

**Comment by Muchiachio** [comment]
What do you mean generic todo item object? And what doesn't work for you?
Nothing much really changed from a regular mvc project, just more separation for testing.

**Comment by punkouter2018** [comment]
I mean since Role/Account are kind of unique objects. If there was a generic simple object like 'Customer' or 'TodoItem' that lived outside of the admin that would help me alot to understand what pieces to copy over when creating a new entity. 

I forgot to run the Rename (to get the admin password)  so I made all the changes and then ran the rename and had some 500 HTTP error.

So Ill try again myself to make this simple non admin object/page and tell you step by step the changes I make and maybe you can help if I get stuck.  I am wondering exactly how much of the Resource/Permissions code is needed. I was pasting that in not sure exactly what it was doing.
