### ISSUE TITLE
gencode using a .net core Console project base on template

### ISSUE THREAD

**Issue by VoTranThi** [NonFactors/MVC6.Template#16]
Hi,

I'm have a little code to make some files base on "src/MvcTemplate.Web/Templates/Module" files folder.
It work like below video:
https://www.youtube.com/watch?v=A09oRUOY_Ac

It just a .net core Console project and I wanna share it but i don't known how to share with you. Are you interest and help me?

Thanks.

**Comment by Muchiachio** [comment]
You can share code on github, but I'm not sure what will this achieve?

**Comment by VoTranThi** [comment]
Hi,

I let it here:
https://github.com/VoTranThi/MVC6.Template/tree/develop/src/MvcTemplate.GenCode

Usage:
1. Make folder for area and controller in MvcTemplate.Objects project
2. Make Model file
3. using Pakage manager console ( Visual Studio) or command Prompt window. run follow command:
   3.1.  locate to mvcTemplate.GenCode:
cd src\MvcTemplate.GenCode

   3.2. Restore nuget Package (skip if you restored, just in first time)
dotnet restore

   3.3. build it to ensure have newest MvcTemplate.Objects.dll file
dotnet build

   3.4 make files by command
dotnet run [Model] [Controller] [Area]

You got it.

**Comment by Muchiachio** [comment]
Thank for the example project on code genning, maybe someone will find it helpful.
