### ISSUE TITLE
http error 500

### ISSUE THREAD

**Issue by GPSGH** [NonFactors/MVC6.Template#17]

**Comment by GPSGH** [comment]
![_20190217220339](https://user-images.githubusercontent.com/24874839/52914166-1c572300-3300-11e9-93dd-08793882aeaf.png)

**Comment by GPSGH** [comment]
can anyone help me? thanks very much

**Comment by Muchiachio** [comment]
You can try removing `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` from the web project `.csproj` file.
