### ISSUE TITLE
[FEATURE] Passwordless

### ISSUE THREAD

**Issue by nicotravassos** [NonFactors/MVC6.Template#18]
Hi @Muchiachio,

Please add passwordless functionality allowing admins to switch between `normal login` or `passwordless`.

This gives a user to Login/Register with there email if account exists send auth code or magiclink to mail address if account does not exist add them to database and send auth code or magiclink to mail address.

**Comment by Muchiachio** [comment]
As mentioned in #19, this is more of a private business application template, where it works inside a private intranet and users are created by the administrators and not on registration principle.
