### ISSUE TITLE
[FEATURE] Add CRUD examples

### ISSUE THREAD

**Issue by nicotravassos** [NonFactors/MVC6.Template#20]
Hi @Muchiachio,

Add basic CRUD examples of say management of products or items or contacts?

And maybe map products with say categories or contacts with groups for example this will show users how to ADD, EDIT, DELETE and VIEW data.

**Comment by Muchiachio** [comment]
There are already two controllers which can be used as a crud example.
Also code generation creates most of the needed stuff automatically.
