### ISSUE TITLE
[ARCHITECTURE] Onion-architecture

### ISSUE THREAD

**Issue by nicotravassos** [NonFactors/MVC6.Template#21]
Hi @Muchiachio,

Maybe consider using onion-architecture [EXAMPLE](https://github.com/EduardoPires/EquinoxProject/tree/master/src)?

**Comment by Muchiachio** [comment]
Can you elaborate what advantages it would bring over current layer separation? And what would change?

**Comment by nicotravassos** [comment]
Hi @nicotravassos, this architecture provides a better way to build applications for better testability, maintainability, and dependability on the infrastructures like databases and services.

**Comment by Muchiachio** [comment]
Well, the current architecture already splits database and services for testability.
So that's why I'm not sure what would change?

**Comment by nicotravassos** [comment]
Correct that example does not provide tests should not have provided such example but [here](https://www.codeguru.com/csharp/csharp/cs_misc/designtechniques/understanding-onion-architecture.html) you can see the Benefits and Drawbacks of Onion Architecture its really up to you if you want to use this architecture or not.

Also may I ask why separate the controllers from the UI?

**Comment by Muchiachio** [comment]
Mostly to make web project a container for static content only. That way it can be switched with other servers like node, while keeping controllers as an API endpoints. Also had scenarios where reloading controllers assembly without redeploying the application itself was beneficial, so I just left it that way.

I think current architecture is very similar to onion one, entities are separated from services and data layer, the only thing missing is repositories which we had before, but it proved to be unnecessary, when generic unit of work methods can provide most of the functionality.

**Comment by nicotravassos** [comment]
I see @Muchiachio 👍.
