### ISSUE TITLE
Cant rename project

### ISSUE THREAD

**Issue by ZoraZora59** [NonFactors/MVC6.Template#23]
6 files were deleted when I run "rename.cmd".
Can anyone teach me how to setup this project?
T_T    plz

**Comment by Muchiachio** [comment]
Yes it deletes the unnecessary files like renaming project, readme and so on.
Does the renamed project became unrunable?

**Comment by ZoraZora59** [comment]
yep, it doesnt work but delete files

**Comment by Muchiachio** [comment]
Maybe it doesn't have permission to create files?

**Comment by ZoraZora59** [comment]
But I did use  administrator privileges when run it.
I saw some error message before it was closed but it was too fast to read.

**Comment by ZoraZora59** [comment]
It seems that my sdk doesn't support .net core 2.2 as target...
How can i fix it?

**Comment by Muchiachio** [comment]
Easiest would be to install 2.2 SDK

**Comment by ZoraZora59** [comment]
XD    Ok,i ll try it.

**Comment by ZoraZora59** [comment]
It work!! Thank you so much!
