### ISSUE TITLE
Database already exist. How can I find the database?

### ISSUE THREAD

**Issue by ZoraZora59** [NonFactors/MVC6.Template#24]
When I run this project first time , system throw an error:
System.Data.SqlClient.SqlException:“There is already an object named 'AuditLog' in the database.”

I want to alter the database , but i don know how to find it.   :(

**Comment by Muchiachio** [comment]
By the default it uses `(localdb)\\mssqllocaldb;Database=Mvc6Template`. I would recommend playing with microsoft provided templates first to get the hang of how everything works and is configured.

**Comment by ZoraZora59** [comment]
I see. Thank you  :P
