### ISSUE TITLE
How to use MVC6.Template

### ISSUE THREAD

**Issue by khawaja74** [NonFactors/MVC6.Template#25]
Hello Folks, Is there a How to use or read me for using MVC6.Template, there are 10 projects in the template and if you can give some direction on using this template it would be just great to put it to good use.

**Comment by Muchiachio** [comment]
The only information available is in this [article](https://www.codeproject.com/Articles/820836/ASP-NET-MVC-Template-introduction) it's a bit outdated, but general ideas still apply.
