### ISSUE TITLE
Non required validation in Resources/View template

### ISSUE THREAD

**Issue by forero08** [NonFactors/MVC6.Template#26]
Hello, 

What is the purpose of the validation in the Resources/view template? [if (i + 1 < properties.Length)](https://github.com/NonFactors/MVC6.Template/blob/e319def4d582151f19272be7b93311ee9467d0a0/src/MvcTemplate.Web/Templates/Module/Resources/View.cshtml#L11). It seems that in any case is executing the same instruction: `@:"@property.Name": "@property.Name.Humanize()"`

**PD:** Excellent project, congratulations. It has a very good structure and the templates are useful for scaffolding.

**Comment by Muchiachio** [comment]
Else statement doesn't add a comma for the last item, some json parsers might not work with trailing one.
