### ISSUE TITLE
Integrate MVC6.Template with dotnet new command

### ISSUE THREAD

**Issue by neman** [NonFactors/MVC6.Template#28]
Have you considered creating this template as part of dotnet new template and publish it as Nuget package?

I have some experience with creating .NET Core template as NuGet package and dotnet new command, so if this is planed feature for some milestone, I can help with it.

For example:
`dotnet new mvc6 -n ApplicationName`

Resource: https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates

**Comment by Muchiachio** [comment]
I guess that would be a better option than having a renaming script, I will look into that.

**Comment by Muchiachio** [comment]
I checked it out, but it still doesn't have github as source  (work in progress on that issue), so I will be postponing this for now. Otherwise it would require building and releasing a nuget package for every commit, which I'm not a fan of doing.

**Comment by neman** [comment]
You can create template from local source, you do not neet nuget for every commit.
Create NuGet only for some releases.

I use it like that.

-i|--install <PATH|NUGET_ID>
Installs a source or template pack from the PATH or NUGET_ID provided. If you want to install a prerelease version of a template package, you need to specify the version in the format of <package-name>::<package-version>. By default, dotnet new passes * for the version, which represents the last stable package version.

**Comment by Muchiachio** [comment]
I guess that's an option, if someone has enough expertise to port `tools\MvcTemplate.Rename\Program.cs` to a dotnet new template feel free to submit a PR. I tried, but it feels like a lot of work to learn and do.

**Comment by neman** [comment]
I can look into it.

**Comment by Muchiachio** [comment]
Do you still have interest in finishing this?
I think it's not worth your time, considering that people don't make new projects every day.

**Comment by neman** [comment]
Closed for now
