### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by webaamir** [NonFactors/MVC6.Template#3]
Dear,

Should I have the database backup file please? Thanks

**Comment by Muchiachio** [comment]
I guess, you get no database errors.
You can create the database by running a `ef` command from data project folder like this:
```
\src\MvcTemplate.Data>dnx ef database update
```
the same should be done for tests project.

**Comment by webaamir** [comment]
Thank you very much for your prompt reply.
Date: Fri, 25 Dec 2015 22:24:10 -0800
