### ISSUE TITLE
Question: Grid default filteration 

### ISSUE THREAD

**Issue by tareq2** [NonFactors/MVC6.Template#30]
Hi,
In version 5 i used to filter the grid by default by creation date and i was using the following code :

```
 var qrys = new System.Collections.Specialized.NameValueCollection();
  qrys.Add("Grid-CreatedOn-GreaterThanOrEqual", DateTime.Now.ToString("dd/MM/yyyy"));
grid.Query = qrys; 
```

But in version 6 it is not working so is there any way to filter the grid by default ?
Thank you

**Comment by Muchiachio** [comment]
If you are using latest sources, then it would be similar to `creation-date-later-than-or-equal`.

**Comment by tareq2** [comment]
It is not working i have used the following code 
 
```
q1 = "created-on-equals=2019%2F05%2F21%20&created-on-op=&created-on-equals=";//Copied as is after doing manual filter
                grid.Query = new QueryCollection(QueryHelpers.ParseQuery(q1));

```

**Comment by Muchiachio** [comment]
I added this to the index page of roles and it seems to works. I'm not sure where are you initializing all this, but maybe something is overriding your values?
```C#
@{
    var html = Html
        .Grid(Model)
        .Build(columns =>
        {
            columns.AddAction("Details", "fa fa-info");
            columns.AddAction("Edit", "fa fa-pencil-alt");
            columns.AddAction("Delete", "fa fa-times");

            columns.AddProperty(model => model.Title);
            columns.AddProperty(model => model.CreationDate);
        })
        .ApplyDefaults();

    html.Grid.Query = new QueryCollection(QueryHelpers.ParseQuery("creation-date-later-than-or-equal=18%2F10%2F2018"));
}

@(html)
```

**Comment by tareq2** [comment]
The diiferent thins is I am using server side code 
```

   IGrid<RoleView> grid = new Grid<RoleView>(Service.GetViews());
  grid.Columns.Add(model => model.Id).Titled("#");
   grid.Columns.Add(model => model.CreationDate).Titled("CreationDate");
var qrys = new System.Collections.Specialized.NameValueCollection();
  qrys.Add(""creation-date-later-than-or-equal", DateTime.Now.ToString("dd/MM/yyyy"));
grid.Query = qrys; 

 foreach (IGridColumn column in grid.Columns)
            {
                column.Filter.IsEnabled = true;
                column.Sort.IsEnabled = true;
            }
          
            return grid;
```
 I have moved the filter code to the markup and now it is working.
But i don't know if am missing something in the above code?

**Comment by Muchiachio** [comment]
Found out that html grid constructor overrides your query with request one.
I will swap initialization so it uses already set grid's query instead, as it should be.

For now you can force filter initialization with `column.Filter.Method = column.Filter.Method;` after enabling the filtering in the for loop.
