### ISSUE TITLE
Active sessions

### ISSUE THREAD

**Issue by mtugnoli** [NonFactors/MVC6.Template#4]
Control of active sessions has always been a big problem,
in the old version of asp.net I was running in the object event "Session"
Now with Asp.Net Core that there are no longer, it seems almost impossible ...

Someone suggested I use the cookies, but it seems not an "elegant solution"
It would be nice to include in your project a function of this kind,
also to be able to manage a kind of license management in the future

**Comment by Muchiachio** [comment]
You mean you want to know which users are currently logged in and have a valid cookie?
Could you share where would you use that kind of information, so I can get a better understanding of the usability of this feature.

Also could you elaborate more on licence management feature, what would it do?

**Comment by mtugnoli** [comment]
No,people tell me to use cookie to remember when enter or leave from site.

What I think is make a kind of licensing system.
I would like to set a "limit" of active sessions, to prevent people enter in mass to my site

**Comment by Muchiachio** [comment]
I tried making a generic session manager for your and various other cases, but it was either duplicating a lot of MVC features or was too specific to be included in generic template. So I will not be adding this feature.
