### ISSUE TITLE
How to deploy to the iis

### ISSUE THREAD

**Issue by leeolevis** [NonFactors/MVC6.Template#5]
Hi 
Now is to run an .exe listening on: http://localhost:5000
How to deploy to the iis?
tks

**Comment by leeolevis** [comment]
And default created project seems to be a little different
Is the default project MvcTemplate.Web.dll, it isn't MvcTemplate.Web.exe

**Comment by Muchiachio** [comment]
I'm usually deploying through visual studio's "Publish" menu or using an automated scripts.
I think microsoft's [official documentation](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis) should be enough for your deployment needs.

**Comment by leeolevis** [comment]
ok tks
