### ISSUE TITLE
Question: Mapping for Grid

### ISSUE THREAD

**Issue by prom3theu5** [NonFactors/MVC6.Template#6]
hi
Nice Template.
I'm extending the Account model, with a property of type AccountInfo.
I have everything working, all the views updated, and the menu rendering my object etc

The issue I have is the Administration -> Accounts -> Index.

RoleId gets mapped to RoleTitle and the rolename gets pulled through.
However - my RealName is always null.

`columns.AddProperty(model => model.Username);
                    columns.AddProperty(model => model.Email);
                    columns.AddProperty(model => model.RealName);
                    columns.AddProperty(model => model.RoleTitle);`

Where AccountInfo is a string which I want to map to AccountInfo.RealName

On AccountView.cs I have
`  public String RealName { get; set; }
        public String RoleTitle { get; set; }`

I don't understand where RoleTitle is getting mapped to Role.Title
Is it automatically mapped from the name?

Thanks

**Comment by Muchiachio** [comment]
Yes, it is automatically mapped by `AutoMapper` library convention.
If you want to automatically map from account info, your property name would have to be `AccountInfoRealName`. Or you can override it in `ObjectMapper`, like this

```C#
Configuration.CreateMap<Account, AccountView>().ForMember(
    account => account.RealName,
    member => member.MapFrom(account => account.AccountInfo.RealName))
```

**Comment by prom3theu5** [comment]
I understand - thanks man :)
