### ISSUE TITLE
Question - how to migrate the project to .NetCore 2.0

### ISSUE THREAD

**Issue by debasisj** [NonFactors/MVC6.Template#7]
Hi 
I can see there is a tool to do that but running the solution does not help much.

Do you have the instructions please?

**Comment by Muchiachio** [comment]
This project does not have migration tool, if you mean `Rename.cmd` it's just a script to rename the project, so you can start implementing your own project with correct namespace and project names.

**Comment by debasisj** [comment]
Thanks for clarifying.

**Comment by debasisj** [comment]
Is that a way to migrate to .Net core 2.0? changing target framework to netcore2.0 in csproj does give error of compatibility

**Comment by Muchiachio** [comment]
Yes changing to `netstandard2.0` and `netcoreapp2.0` and updating package references to `2.0` shoudl be enough, unless your are using API's which had breaking changes made between `1.x` and `2.0`.
