### ISSUE TITLE
Question - Database Migration

### ISSUE THREAD

**Issue by debasisj** [NonFactors/MVC6.Template#8]
Hi,

After I changed the configuration.json from localdb to actual DB, running update-database throws below error - so how i can migrate ?

PM> update-database
Unable to create an object of type 'Context'. Add an implementation of 'IDesignTimeDbContextFactory<Context>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

**Comment by Muchiachio** [comment]
You have to run update database from the data project folder with `dotnet` command.
`dotnet ef database update`
